Also support single location in Implementation/TypeDefinition/Definition response
fhs/acme-lsp pull request #45
Opened 2021-11-12 02:30 UTC by tw4452852

According to the LSP 3.16 spec, in following responses, both `Location` and `[]Location` are allowed:

- [Goto Implementation Request](https://microsoft.github.io/language-server-protocol/specification#textDocument_implementation)
- [Goto Type Definition Request](https://microsoft.github.io/language-server-protocol/specification#textDocument_typeDefinition)
- [Goto Definition Request](https://microsoft.github.io/language-server-protocol/specification#textDocument_definition)

BTW, I encountered this issue when using Zig's language server (zls).

Signed-off-by: Tw <wei.tan@intel.com>

2021-11-28 05:01 UTC, fhs requested changes
Thanks.

I'm slightly worried about making changes to auto-generated code (`tsserver.go`), but I think we need a better solution than coping from gopls. There is some discussion upstream here: https://github.com/microsoft/language-server-protocol/issues/67

2021-11-30 06:51 UTC, tw4452852 commented on internal/lsp/protocol/compat.go
> +type Locations struct {
Yes, this is nicer, thanks.

2021-11-30 06:51 UTC, tw4452852 commented on internal/lsp/protocol/compat.go
> +	if len(d) == 0 {
Good catch!

2021-12-01 01:00 UTC, fhs approved these changes

2021-12-01 01:00 UTC, merged